"""add cascade delete to chunks

Revision ID: 0f97e309ab61
Revises: f9355b59d1a1
Create Date: 2026-05-22 20:52:09.568341

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0f97e309ab61"
down_revision: Union[str, Sequence[str], None] = "f9355b59d1a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("chunks", "document_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_constraint(op.f("chunks_document_id_fkey"), "chunks", type_="foreignkey")
    op.create_foreign_key(
        None, "chunks", "documents", ["document_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chunks", type_="foreignkey")
    op.create_foreign_key(
        op.f("chunks_document_id_fkey"), "chunks", "documents", ["document_id"], ["id"]
    )
    op.alter_column("chunks", "document_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
